### ISSUE TITLE
Front end resume submissions are not indexed

### ISSUE THREAD

**Issue by jchristopher** [searchwp/searchwp-wp-job-manager-integration#3]
Fix from @BrElio via ticket `7479`

Resume submissions are auto-approved, but not indexed until you visit the SearchWP settings screen. This is because SearchWP isn't observing this action. The entries would get picked up on the next iteration of the indexer but it would be better to have it happen in real time with something like:

```php
add_action( 'save_post', function(){
    if( isset( $_REQUEST['resume_manager_form'] ) && 'submit-resume' == $_REQUEST['resume_manager_form'] ){
        SWP()->trigger_index();
    }
});
```

**Comment by BrElio** [comment]
Job listings have the same issue. The save_post is triggered twice though. Once for submitting the data and then again after reviewing the data in the front end.
This should work for resumes and job listings triggering the index only once for job listings:

`add_action( 'save_post', function(){
	if( ( isset( $_REQUEST['resume_manager_form'] ) && 'submit-resume' == $_REQUEST['resume_manager_form'] )
		|| isset( $_REQUEST['job_manager_form'] ) && 'submit-job' == $_REQUEST['job_manager_form'] && isset( $_REQUEST['job_id'] ) && $_REQUEST['job_id'] ){
		SWP()->trigger_index();
	}
});`
